/**
 * API keys — the data-layer credential surface. Keys are generated by a
 * server action (raw key shown once, only the hash is stored) and revoked
 * by deleting the row.
 */

import { useState } from 'react'
import { useQuery, useMutations, getAuthToken } from 'deepspace'
import { KeyRound } from 'lucide-react'
import {
  Badge,
  Button,
  Input,
  Modal,
  ConfirmModal,
  EmptyState,
  SkeletonList,
  useToast,
} from '@/components/ui'
import { PageHeader, SectionLabel } from '../../components/PageHeader'
import type { ApiKey } from '../../types'

export default function ApiKeysPage() {
  const { records: keys, status } = useQuery<ApiKey>('api_keys', { orderBy: 'createdAt', orderDir: 'desc' })
  const { remove } = useMutations<ApiKey>('api_keys')
  const { success, error } = useToast()

  const [label, setLabel] = useState('')
  const [generating, setGenerating] = useState(false)
  const [rawKey, setRawKey] = useState<string | null>(null)
  const [revoking, setRevoking] = useState<string | null>(null)

  async function generate() {
    if (!label.trim()) return
    setGenerating(true)
    try {
      const res = await fetch('/api/actions/generateApiKey', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${await getAuthToken()}`,
        },
        body: JSON.stringify({ label: label.trim() }),
      })
      const json = (await res.json()) as { success: boolean; data?: { rawKey: string }; error?: string }
      if (!json.success || !json.data) throw new Error(json.error ?? 'unknown error')
      setRawKey(json.data.rawKey)
      setLabel('')
      success('Key generated', 'Copy it now — it will not be shown again.')
    } catch (err) {
      error('Generation failed', String(err))
    } finally {
      setGenerating(false)
    }
  }

  const loading = status === 'loading'
  const list = keys ?? []

  return (
    <div className="flex min-h-full flex-col">
      <PageHeader
        title="API"
        meta={<span>{loading ? '' : `${list.length} ${list.length === 1 ? 'key' : 'keys'}`}</span>}
      />

      <div className="flex-1 px-4 py-4 sm:px-6">
        <div className="mx-auto max-w-3xl space-y-6">
          <p className="text-[13px] text-muted-foreground">
            Bearer credentials for the data-layer API. Query mentions with{' '}
            <code className="rounded bg-muted px-1 py-0.5 font-mono text-[11px] text-foreground">
              POST /api/v2/mentions
            </code>
            .
          </p>

          {/* Generate row */}
          <div className="rounded-lg border border-border bg-card/50 p-3">
            <div className="flex gap-2">
              <Input
                data-testid="key-label"
                value={label}
                onChange={(e) => setLabel(e.target.value)}
                placeholder="Key label, e.g. 'zapier-prod'"
                className="h-9 text-[13px]"
              />
              <Button
                size="sm"
                data-testid="generate-key"
                onClick={generate}
                disabled={generating || !label.trim()}
              >
                {generating ? 'Generating…' : 'Generate key'}
              </Button>
            </div>
          </div>

          {/* Key list */}
          <section className="space-y-2">
            <SectionLabel>Keys</SectionLabel>

            {loading && <SkeletonList rows={3} />}

            {!loading && list.length === 0 && (
              <div className="rounded-lg border border-border">
                <EmptyState
                  icon={<KeyRound aria-hidden />}
                  title="No API keys"
                  description="Generate one to query your mentions programmatically."
                />
              </div>
            )}

            {!loading && list.length > 0 && (
              <ul className="divide-y divide-border rounded-lg border border-border bg-card/50">
                {list.map((k) => (
                  <li
                    key={k.recordId}
                    data-testid="key-row"
                    className="flex items-center gap-3 px-4 py-3"
                  >
                    <div className="min-w-0 flex-1">
                      <div className="flex flex-wrap items-baseline gap-x-2 gap-y-1">
                        <span className="text-[13px] font-medium text-foreground">{k.data.label}</span>
                        <span className="font-mono text-[11px] text-muted-foreground">
                          {k.data.prefix}…
                        </span>
                        {!k.data.is_active && (
                          <Badge variant="secondary" size="sm">
                            revoked
                          </Badge>
                        )}
                      </div>
                      <div className="mt-1 flex flex-wrap items-center gap-x-3 font-mono text-[11px] text-muted-foreground/80">
                        {k.createdAt && <span>created {new Date(k.createdAt).toLocaleString()}</span>}
                        <span>
                          {k.data.last_used_at
                            ? `last used ${new Date(k.data.last_used_at).toLocaleString()}`
                            : 'never used'}
                        </span>
                      </div>
                    </div>
                    <Button
                      size="sm"
                      variant="ghost"
                      data-testid="revoke-key"
                      onClick={() => setRevoking(k.recordId)}
                      className="h-7 px-2.5 text-xs text-muted-foreground hover:bg-destructive/10 hover:text-destructive"
                    >
                      Revoke
                    </Button>
                  </li>
                ))}
              </ul>
            )}
          </section>

          {/* Quick start */}
          <section className="space-y-2">
            <SectionLabel>Quick start</SectionLabel>
            <div className="overflow-x-auto rounded-lg border border-border bg-card p-4">
              <pre className="font-mono text-[12px] leading-relaxed text-foreground">
                {`curl -X POST ${typeof window !== 'undefined' ? window.location.origin : ''}/api/v2/mentions \\
  -H "Authorization: Bearer olk_..." \\
  -H "Content-Type: application/json" \\
  -d '{"filters":{"sentiment":["negative"]},"limit":25}'`}
              </pre>
            </div>
          </section>
        </div>
      </div>

      <Modal open={rawKey !== null} onClose={() => setRawKey(null)}>
        <Modal.Header onClose={() => setRawKey(null)}>
          <Modal.Title>Your new API key</Modal.Title>
          <Modal.Description>
            Copy it now — only a hash is stored, so it cannot be shown again.
          </Modal.Description>
        </Modal.Header>
        <Modal.Body>
          <div className="rounded-lg border border-primary/30 bg-primary/[0.06] p-3">
            <code data-testid="raw-key" className="block break-all font-mono text-[12px] leading-relaxed text-foreground">
              {rawKey}
            </code>
          </div>
          <div className="mt-4 flex justify-end gap-2">
            <Button
              size="sm"
              variant="secondary"
              onClick={() => {
                if (rawKey) void navigator.clipboard.writeText(rawKey)
                success('Copied')
              }}
            >
              Copy
            </Button>
            <Button size="sm" onClick={() => setRawKey(null)}>
              Done
            </Button>
          </div>
        </Modal.Body>
      </Modal>

      <ConfirmModal
        open={revoking !== null}
        onClose={() => setRevoking(null)}
        onConfirm={async () => {
          if (revoking) {
            await remove(revoking)
            success('Key revoked')
          }
          setRevoking(null)
        }}
        title="Revoke this key?"
        description="Requests using it will get 401 immediately. This cannot be undone."
        confirmText="Revoke"
      />
    </div>
  )
}
