/**
 * API keys — the data-layer credential surface. Keys are generated by a
 * server action (raw key shown once, only the hash is stored) and revoked
 * by deleting the row.
 */

import { useState } from 'react'
import { useQuery, useMutations, getAuthToken } from 'deepspace'
import { Badge, Button, Input, Modal, ConfirmModal, EmptyState, useToast } from '@/components/ui'
import type { ApiKey } from '../../types'

export default function ApiKeysPage() {
  const { records: keys, status } = useQuery<ApiKey>('api_keys', { orderBy: 'createdAt', orderDir: 'desc' })
  const { remove } = useMutations<ApiKey>('api_keys')
  const { success, error } = useToast()

  const [label, setLabel] = useState('')
  const [generating, setGenerating] = useState(false)
  const [rawKey, setRawKey] = useState<string | null>(null)
  const [revoking, setRevoking] = useState<string | null>(null)

  async function generate() {
    if (!label.trim()) return
    setGenerating(true)
    try {
      const res = await fetch('/api/actions/generateApiKey', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${await getAuthToken()}`,
        },
        body: JSON.stringify({ label: label.trim() }),
      })
      const json = (await res.json()) as { success: boolean; data?: { rawKey: string }; error?: string }
      if (!json.success || !json.data) throw new Error(json.error ?? 'unknown error')
      setRawKey(json.data.rawKey)
      setLabel('')
      success('Key generated', 'Copy it now — it will not be shown again.')
    } catch (err) {
      error('Generation failed', String(err))
    } finally {
      setGenerating(false)
    }
  }

  return (
    <div className="min-h-full bg-background text-foreground">
      <div className="mx-auto max-w-3xl px-6 py-12">
        <h1 className="text-3xl font-bold tracking-tight">API keys</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Bearer credentials for the data-layer API. Query mentions with{' '}
          <code className="rounded bg-muted px-1.5 py-0.5 text-xs">POST /api/v2/mentions</code>.
        </p>

        <div className="mt-6 flex gap-2">
          <Input
            data-testid="key-label"
            value={label}
            onChange={(e) => setLabel(e.target.value)}
            placeholder="Key label, e.g. 'zapier-prod'"
          />
          <Button data-testid="generate-key" onClick={generate} disabled={generating || !label.trim()}>
            {generating ? 'Generating…' : 'Generate key'}
          </Button>
        </div>

        <div className="mt-8">
          {status !== 'loading' && (keys ?? []).length === 0 && (
            <EmptyState title="No API keys" description="Generate one to query your mentions programmatically." />
          )}
          <ul className="space-y-2">
            {(keys ?? []).map((k) => (
              <li
                key={k.recordId}
                data-testid="key-row"
                className="flex items-center justify-between gap-3 rounded-lg border border-border bg-card p-3"
              >
                <div>
                  <div className="flex items-center gap-2">
                    <span className="font-medium">{k.data.label}</span>
                    <code className="rounded bg-muted px-1.5 py-0.5 text-xs">{k.data.prefix}…</code>
                    {!k.data.is_active && <Badge variant="secondary">revoked</Badge>}
                  </div>
                  <p className="mt-0.5 text-xs text-muted-foreground">
                    {k.data.last_used_at
                      ? `last used ${new Date(k.data.last_used_at).toLocaleString()}`
                      : 'never used'}
                  </p>
                </div>
                <Button size="sm" variant="ghost" data-testid="revoke-key" onClick={() => setRevoking(k.recordId)}>
                  Revoke
                </Button>
              </li>
            ))}
          </ul>
        </div>

        <div className="mt-10 rounded-lg border border-border bg-card p-4 text-sm">
          <h2 className="font-semibold">Quick start</h2>
          <pre className="mt-2 overflow-x-auto rounded bg-muted p-3 text-xs">
            {`curl -X POST ${typeof window !== 'undefined' ? window.location.origin : ''}/api/v2/mentions \\
  -H "Authorization: Bearer olk_..." \\
  -H "Content-Type: application/json" \\
  -d '{"filters":{"sentiment":["negative"]},"limit":25}'`}
          </pre>
        </div>
      </div>

      <Modal open={rawKey !== null} onClose={() => setRawKey(null)}>
        <Modal.Header onClose={() => setRawKey(null)}>
          <Modal.Title>Your new API key</Modal.Title>
          <Modal.Description>
            Copy it now — only a hash is stored, so it cannot be shown again.
          </Modal.Description>
        </Modal.Header>
        <Modal.Body>
          <code data-testid="raw-key" className="block break-all rounded bg-muted p-3 font-mono text-sm">
            {rawKey}
          </code>
          <div className="mt-4 flex justify-end gap-2">
            <Button
              variant="secondary"
              onClick={() => {
                if (rawKey) void navigator.clipboard.writeText(rawKey)
                success('Copied')
              }}
            >
              Copy
            </Button>
            <Button onClick={() => setRawKey(null)}>Done</Button>
          </div>
        </Modal.Body>
      </Modal>

      <ConfirmModal
        open={revoking !== null}
        onClose={() => setRevoking(null)}
        onConfirm={async () => {
          if (revoking) {
            await remove(revoking)
            success('Key revoked')
          }
          setRevoking(null)
        }}
        title="Revoke this key?"
        description="Requests using it will get 401 immediately. This cannot be undone."
        confirmText="Revoke"
      />
    </div>
  )
}
